//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjeRentACar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Arac
    {
        public int id { get; set; }
        public string Marka { get; set; }
        public string Plaka { get; set; }
        public string Yıl { get; set; }
        public string Yakıt_tipi { get; set; }
        public string Durum { get; set; }
        public string Vites { get; set; }
        public string img { get; set; }
    }
}
