//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjeRentACar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Musteri
    {
        public int id { get; set; }
        public string Ad_Soyad { get; set; }
        public string Email { get; set; }
        public string Dogum_Yili { get; set; }
        public string Telefon { get; set; }
        public Nullable<int> sehir_id { get; set; }
        public Nullable<int> ilce_id { get; set; }
    
        public virtual Sehir Sehir { get; set; }
        public virtual ilce ilce { get; set; }
    }
}
